services:
  backend:
    build: .
    volumes:
      - ./svgs:/app/svgs:ro
      - ./mng.db:/app/mng.db:rw
    expose:
      - "8080"
    networks:
      - app_net
    labels:
      pingoo.service: website

  pingoo:
    image: pingooio/pingoo:latest
    restart: unless-stopped
    network_mode: "host"
    volumes: 
      - ./pingoo.yml:/etc/pingoo/pingoo.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - backend

networks:
  app_net:
    driver: bridge
